/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MENSAJE_H_RPCGEN
#define _MENSAJE_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct response {
	struct {
		u_int v1_len;
		char *v1_val;
	} v1;
	int N;
	struct {
		u_int v2_len;
		double *v2_val;
	} v2;
	int error;
};
typedef struct response response;

struct request {
	int key;
	struct {
		u_int v1_len;
		char *v1_val;
	} v1;
	int N;
	struct {
		u_int v2_len;
		double *v2_val;
	} v2;
};
typedef struct request request;

#define LIST_SERVICE 99
#define LIST_SERVICE_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define init_rpc 0
extern  enum clnt_stat init_rpc_1(int *, CLIENT *);
extern  bool_t init_rpc_1_svc(int *, struct svc_req *);
#define set_value_rpc 1
extern  enum clnt_stat set_value_rpc_1(struct request , int *, CLIENT *);
extern  bool_t set_value_rpc_1_svc(struct request , int *, struct svc_req *);
#define get_value_rpc 2
extern  enum clnt_stat get_value_rpc_1(int , struct response *, CLIENT *);
extern  bool_t get_value_rpc_1_svc(int , struct response *, struct svc_req *);
#define modify_value_rpc 3
extern  enum clnt_stat modify_value_rpc_1(struct request , int *, CLIENT *);
extern  bool_t modify_value_rpc_1_svc(struct request , int *, struct svc_req *);
#define delete_key_rpc 4
extern  enum clnt_stat delete_key_rpc_1(int , int *, CLIENT *);
extern  bool_t delete_key_rpc_1_svc(int , int *, struct svc_req *);
#define exist_rpc 5
extern  enum clnt_stat exist_rpc_1(int , int *, CLIENT *);
extern  bool_t exist_rpc_1_svc(int , int *, struct svc_req *);
extern int list_service_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define init_rpc 0
extern  enum clnt_stat init_rpc_1();
extern  bool_t init_rpc_1_svc();
#define set_value_rpc 1
extern  enum clnt_stat set_value_rpc_1();
extern  bool_t set_value_rpc_1_svc();
#define get_value_rpc 2
extern  enum clnt_stat get_value_rpc_1();
extern  bool_t get_value_rpc_1_svc();
#define modify_value_rpc 3
extern  enum clnt_stat modify_value_rpc_1();
extern  bool_t modify_value_rpc_1_svc();
#define delete_key_rpc 4
extern  enum clnt_stat delete_key_rpc_1();
extern  bool_t delete_key_rpc_1_svc();
#define exist_rpc 5
extern  enum clnt_stat exist_rpc_1();
extern  bool_t exist_rpc_1_svc();
extern int list_service_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_response (XDR *, response*);
extern  bool_t xdr_request (XDR *, request*);

#else /* K&R C */
extern bool_t xdr_response ();
extern bool_t xdr_request ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MENSAJE_H_RPCGEN */
