/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_H_RPCGEN
#define _RPC_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct response {
	int check;
	char *value1;
	int value2;
	double value3;
};
typedef struct response response;

struct set_value_rpc_1_argument {
	int key;
	char *value1;
	int value2;
	double value3;
};
typedef struct set_value_rpc_1_argument set_value_rpc_1_argument;

struct modify_value_rpc_1_argument {
	int key;
	char *value1;
	int value2;
	double value3;
};
typedef struct modify_value_rpc_1_argument modify_value_rpc_1_argument;

struct copy_key_rpc_1_argument {
	int key1;
	int key2;
};
typedef struct copy_key_rpc_1_argument copy_key_rpc_1_argument;

#define SERVER_FUNC 99
#define SERVER_FUNC_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define init_rpc 1
extern  enum clnt_stat init_rpc_1(struct response *, CLIENT *);
extern  bool_t init_rpc_1_svc(struct response *, struct svc_req *);
#define set_value_rpc 2
extern  enum clnt_stat set_value_rpc_1(int , char *, int , double , struct response *, CLIENT *);
extern  bool_t set_value_rpc_1_svc(int , char *, int , double , struct response *, struct svc_req *);
#define get_value_rpc 3
extern  enum clnt_stat get_value_rpc_1(int , struct response *, CLIENT *);
extern  bool_t get_value_rpc_1_svc(int , struct response *, struct svc_req *);
#define modify_value_rpc 4
extern  enum clnt_stat modify_value_rpc_1(int , char *, int , double , struct response *, CLIENT *);
extern  bool_t modify_value_rpc_1_svc(int , char *, int , double , struct response *, struct svc_req *);
#define delete_key_rpc 5
extern  enum clnt_stat delete_key_rpc_1(int , struct response *, CLIENT *);
extern  bool_t delete_key_rpc_1_svc(int , struct response *, struct svc_req *);
#define exist_rpc 6
extern  enum clnt_stat exist_rpc_1(int , struct response *, CLIENT *);
extern  bool_t exist_rpc_1_svc(int , struct response *, struct svc_req *);
#define copy_key_rpc 7
extern  enum clnt_stat copy_key_rpc_1(int , int , struct response *, CLIENT *);
extern  bool_t copy_key_rpc_1_svc(int , int , struct response *, struct svc_req *);
extern int server_func_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define init_rpc 1
extern  enum clnt_stat init_rpc_1();
extern  bool_t init_rpc_1_svc();
#define set_value_rpc 2
extern  enum clnt_stat set_value_rpc_1();
extern  bool_t set_value_rpc_1_svc();
#define get_value_rpc 3
extern  enum clnt_stat get_value_rpc_1();
extern  bool_t get_value_rpc_1_svc();
#define modify_value_rpc 4
extern  enum clnt_stat modify_value_rpc_1();
extern  bool_t modify_value_rpc_1_svc();
#define delete_key_rpc 5
extern  enum clnt_stat delete_key_rpc_1();
extern  bool_t delete_key_rpc_1_svc();
#define exist_rpc 6
extern  enum clnt_stat exist_rpc_1();
extern  bool_t exist_rpc_1_svc();
#define copy_key_rpc 7
extern  enum clnt_stat copy_key_rpc_1();
extern  bool_t copy_key_rpc_1_svc();
extern int server_func_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_response (XDR *, response*);
extern  bool_t xdr_set_value_rpc_1_argument (XDR *, set_value_rpc_1_argument*);
extern  bool_t xdr_modify_value_rpc_1_argument (XDR *, modify_value_rpc_1_argument*);
extern  bool_t xdr_copy_key_rpc_1_argument (XDR *, copy_key_rpc_1_argument*);

#else /* K&R C */
extern bool_t xdr_response ();
extern bool_t xdr_set_value_rpc_1_argument ();
extern bool_t xdr_modify_value_rpc_1_argument ();
extern bool_t xdr_copy_key_rpc_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_H_RPCGEN */
